[build]
command = "cargo install trunk && trunk build --release"
publish = "dist"

[build.environment]
  CARGO_HOME = "/opt/buildhome/.cargo"

[context.production]
  cache = ["/opt/buildhome/.cargo/.crates.toml", "/opt/buildhome/.cargo/.crates2.json"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "https://rpeabs.net/cs2autoexec/:splat"
status = 301
force = true
